#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class TextBlock;
                ref class TextBox;
                ref class ProgressBar;
                ref class Button;
                ref class AutoSuggestBox;
            }
        }
    }
}

namespace SeboApp
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ LayoutGrid;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ textBlock;
        private: ::Windows::UI::Xaml::Controls::TextBox^ resultTextBox;
        private: ::Windows::UI::Xaml::Controls::ProgressBar^ progressBar;
        private: ::Windows::UI::Xaml::Controls::Button^ CS40Path;
        private: ::Windows::UI::Xaml::Controls::Button^ CS45Path;
        private: ::Windows::UI::Xaml::Controls::AutoSuggestBox^ searchTextBox;
    };
}

